-- Migration: Sistema profissional de gêneros
ALTER TABLE public.generos ADD COLUMN IF NOT EXISTS slug text UNIQUE, description text, image_url text, banner_url text, display_order integer DEFAULT 0, popularity_score numeric(5,2) DEFAULT 0, is_active boolean DEFAULT true, metadata jsonb DEFAULT '{}', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), tmdb_id integer, content_count integer DEFAULT 0, avg_rating numeric(3,1) DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_generos_slug ON public.generos(slug) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_generos_popularity ON public.generos(popularity_score DESC) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_generos_display_order ON public.generos(display_order ASC, nome ASC);
CREATE OR REPLACE FUNCTION generate_slug(p_text text) RETURNS text LANGUAGE plpgsql AS $$ DECLARE v_slug text; BEGIN v_slug := lower(trim(regexp_replace(p_text, '[^a-zA-Z0-9\s]', '', 'g'))); v_slug := regexp_replace(v_slug, '\s+', '-', 'g'); RETURN v_slug; END; $$;
CREATE OR REPLACE FUNCTION set_genero_slug() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN IF NEW.slug IS NULL OR NEW.slug = '' THEN NEW.slug := generate_slug(NEW.nome); END IF; RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS generos_auto_slug ON public.generos; CREATE TRIGGER generos_auto_slug BEFORE INSERT OR UPDATE ON public.generos FOR EACH ROW EXECUTE FUNCTION set_genero_slug();
CREATE TABLE IF NOT EXISTS public.cinema_genres (id bigint generated always as identity PRIMARY KEY, cinema_id integer NOT NULL REFERENCES public.cinema(id) ON DELETE CASCADE, genre_id text NOT NULL REFERENCES public.generos(id) ON DELETE CASCADE, is_primary boolean DEFAULT false, created_at timestamptz DEFAULT now(), UNIQUE(cinema_id, genre_id));
CREATE TABLE IF NOT EXISTS public.series_genres (id bigint generated always as identity PRIMARY KEY, series_id integer NOT NULL REFERENCES public.series(id_n) ON DELETE CASCADE, genre_id text NOT NULL REFERENCES public.generos(id) ON DELETE CASCADE, is_primary boolean DEFAULT false, created_at timestamptz DEFAULT now(), UNIQUE(series_id, genre_id));
CREATE INDEX IF NOT EXISTS idx_cinema_genres_cinema_id ON public.cinema_genres(cinema_id); CREATE INDEX IF NOT EXISTS idx_cinema_genres_genre_id ON public.cinema_genres(genre_id);
CREATE INDEX IF NOT EXISTS idx_series_genres_series_id ON public.series_genres(series_id); CREATE INDEX IF NOT EXISTS idx_series_genres_genre_id ON public.series_genres(genre_id);
CREATE OR REPLACE FUNCTION get_all_genres(p_limit integer DEFAULT 100) RETURNS TABLE (id text, nome text, slug text, description text, image_url text, popularity_score numeric, content_count integer) LANGUAGE sql SECURITY DEFINER STABLE AS $$ SELECT g.id, g.nome, g.slug, g.description, g.image_url, g.popularity_score, g.content_count FROM public.generos g WHERE g.is_active = true ORDER BY g.display_order ASC, g.popularity_score DESC, g.nome ASC LIMIT p_limit; $$;
CREATE OR REPLACE FUNCTION get_genre_by_slug(p_slug text) RETURNS TABLE (id text, nome text, slug text, description text, image_url text, banner_url text, popularity_score numeric, content_count integer, avg_rating numeric) LANGUAGE sql SECURITY DEFINER STABLE AS $$ SELECT g.id, g.nome, g.slug, g.description, g.image_url, g.banner_url, g.popularity_score, g.content_count, g.avg_rating FROM public.generos g WHERE g.slug = p_slug AND g.is_active = true LIMIT 1; $$;
CREATE OR REPLACE FUNCTION get_trending_genres(p_limit integer DEFAULT 10) RETURNS TABLE (id text, nome text, slug text, popularity_score numeric, content_count integer) LANGUAGE sql SECURITY DEFINER STABLE AS $$ SELECT g.id, g.nome, g.slug, g.popularity_score, g.content_count FROM public.generos g WHERE g.is_active = true AND g.popularity_score > 0 ORDER BY g.popularity_score DESC, g.content_count DESC LIMIT p_limit; $$;
CREATE OR REPLACE FUNCTION sync_genre(p_id text, p_nome text, p_tmdb_id integer DEFAULT NULL) RETURNS text LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN INSERT INTO public.generos (id, nome, tmdb_id, slug) VALUES (p_id, p_nome, p_tmdb_id, generate_slug(p_nome)) ON CONFLICT (id) DO UPDATE SET nome = EXCLUDED.nome, tmdb_id = COALESCE(EXCLUDED.tmdb_id, public.generos.tmdb_id), updated_at = NOW() RETURNING id; END; $$;
