// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Helper to check if JWT token is expired
function isTokenExpired(token: string): boolean {
  try {
    const base64Url = token.split('.')[1];
    const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
    const jsonPayload = decodeURIComponent(atob(base64).split('').map(c => {
      return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join(''));
    const { exp } = JSON.parse(jsonPayload);
    return exp && Date.now() >= exp * 1000;
  } catch {
    return true; // If can't parse, consider expired
  }
}

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Verificar se as variáveis de ambiente estão definidas
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('[Supabase] ERRO: Variáveis de ambiente não definidas!');
  console.error('[Supabase] VITE_SUPABASE_URL:', SUPABASE_URL ? 'Definida' : 'FALTANDO');
  console.error('[Supabase] VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? 'Definida' : 'FALTANDO');
}

// Fetch com timeout que garante headers do Supabase
async function fetchWithTimeout(url: string, options: RequestInit, timeout: number) {
  
  const controller = new AbortController();
  const id = setTimeout(() => controller.abort(), timeout);
  
  // Normalizar headers para objeto plano
  const existingHeaders: Record<string, string> = {};
  if (options.headers) {
    if (options.headers instanceof Headers) {
      options.headers.forEach((value, key) => {
        existingHeaders[key.toLowerCase()] = value;
      });
    } else if (Array.isArray(options.headers)) {
      options.headers.forEach(([key, value]) => {
        existingHeaders[key.toLowerCase()] = value;
      });
    } else {
      Object.entries(options.headers).forEach(([key, value]) => {
        if (value !== undefined) {
          existingHeaders[key.toLowerCase()] = String(value);
        }
      });
    }
  }
  
  // Check if existing authorization token is expired - remove it if so
  const authHeader = existingHeaders['authorization'];
  if (authHeader && authHeader.startsWith('Bearer ')) {
    const token = authHeader.replace('Bearer ', '');
    if (isTokenExpired(token)) {
      console.log('[Supabase Fetch] Token expirado removido');
      delete existingHeaders['authorization'];
    }
  }
  
  // Headers obrigatórios do Supabase
  const supabaseHeaders: Record<string, string> = {
    'apikey': SUPABASE_PUBLISHABLE_KEY,
    'x-client-info': 'cinecasa-web',
  };
  
  // Only add anonymous authorization if no valid user token exists
  if (!existingHeaders['authorization']) {
    supabaseHeaders['authorization'] = `Bearer ${SUPABASE_PUBLISHABLE_KEY}`;
  }
  
  // Mesclar: headers do Supabase têm prioridade para apikey
  const headers: Record<string, string> = {
    ...supabaseHeaders,
    ...existingHeaders,
  };
  
  // DEBUG: Log headers being sent
  console.log('[Supabase Fetch] URL:', url);
  console.log('[Supabase Fetch] Headers:', headers);
  console.log('[Supabase Fetch] apikey presente:', !!headers['apikey']);
  console.log('[Supabase Fetch] authorization presente:', !!headers['authorization']);
  
  try {
    const response = await fetch(url, {
      ...options,
      headers,
      signal: controller.signal,
    });
    if (response.status === 401) {
      console.error('[Supabase Fetch] 401 Unauthorized - Headers enviados:', headers);
    }
    clearTimeout(id);
    return response;
  } catch (error) {
    clearTimeout(id);
    throw error;
  }
}

// Singleton pattern para evitar múltiplas instâncias
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = (() => {
  if (!supabaseInstance) {
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: false,
        detectSessionInUrl: false,
        flowType: 'implicit',
        debug: false,
      },
      realtime: {
        params: {
          eventsPerSecond: 1,
        },
        timeout: 5000,
      },
      global: {
        fetch: (url, options) => {
          return fetchWithTimeout(url as string, options as RequestInit, 30000);
        },
      },
    });
    console.log('[Supabase] Nova instância criada com headers garantidos');
  } else {
    console.log('[Supabase] Reutilizando instância existente');
  }
  return supabaseInstance;
})();

// Função utilitária para retry de operações Supabase
export async function supabaseWithRetry<T>(
  operation: () => Promise<T>,
  retries = 2,
  delay = 1000
): Promise<T> {
  let lastError;
  
  for (let i = 0; i < retries; i++) {
    try {
      return await operation();
    } catch (error: any) {
      lastError = error;
      console.log(`[Supabase] Tentativa ${i + 1} falhou:`, error.message);
      
      // Só retry em erros de rede, não em erros de auth
      if (error.message?.includes('Failed to fetch') || 
          error.message?.includes('timeout') ||
          error.message?.includes('NetworkError')) {
        if (i < retries - 1) {
          await new Promise(resolve => setTimeout(resolve, delay * (i + 1)));
          continue;
        }
      }
      throw error;
    }
  }
  
  throw lastError;
}